# Generated by Django 4.0.4 on 2022-05-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('statusStartDate', models.DateField(null=True)),
                ('statusEndDate', models.DateField(null=True)),
            ],
        ),
    ]
