# Generated by Django 4.0.4 on 2022-05-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='p_pic',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_pic/hotel profile/'),
        ),
    ]
