# Generated by Django 4.0.4 on 2022-05-21 07:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_hotels_p_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodmenu',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='foodmenu',
            name='menuItems',
        ),
        migrations.RemoveField(
            model_name='foodmenu',
            name='startDate',
        ),
        migrations.AddField(
            model_name='foodmenu',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodmenu',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodmenu',
            name='type',
            field=models.CharField(choices=[('appetizer', 'appetizer'), ('entree', 'entree'), ('dessert', 'dessert')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
